version: '3.9'
services:

  #MYSQL
  mysql:
    build: "./docker/mysql"
    container_name: "${appName}-mysql"
    restart: "always"
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command:
      [
        "mysqld",
        "--max_allowed_packet=32505856",
        "--sql_mode="
      ]
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"

  #PHP
  php:
    build: "./docker/php/"
    container_name: "${appName}-php"
    restart: "always"
    depends_on:
      - mysql
    volumes:
      #pasta do sistema
      - "./app:/var/www/public"
      #configurações php.ini
      - "./docker/php/configs/php.ini:/usr/local/etc/php/php.ini"
      #configurações de performance php
      - "./docker/php/configs/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"

  #NGINX
  nginx:
    build: "./docker/nginx/"
    container_name: "${appName}-nginx"
    restart: "always"
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_SSL}:443"
    depends_on:
      - mysql
      - php
    links:
      - php
    volumes:
      #pasta do sistema
      - "./app:/var/www/public"
      #configurações nginx
      - "./docker/nginx/configs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/configs/etc/nginx/conf.d/config.conf:/etc/nginx/conf.d/config.conf"
      - "./docker/nginx/configs/etc/nginx/conf.d/gzip.conf:/etc/nginx/conf.d/gzip.conf"
      #logs de erros
      - "./docker/nginx/log/:/var/log/nginx"
